"""Symmetry operations for Rubik's Cube data augmentation."""

from __future__ import annotations
import numpy as np
from typing import List, Tuple, Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from .cube import RubiksCube


class CubeSymmetry:
    """
    Handles the 24-element rotational symmetry group of the cube.

    The cube has 24 orientation-preserving symmetries:
    - 1 identity
    - 6 face rotations (90° and 270° around 3 axes)
    - 3 face rotations (180° around 3 axes)
    - 8 vertex rotations (120° and 240° around 4 body diagonals)
    - 6 edge rotations (180° around 6 edge-midpoint axes)

    These symmetries can be used for:
    1. Data augmentation during training
    2. Reducing the effective state space
    3. Finding canonical state representations
    """

    # Face indices
    UP, DOWN, FRONT, BACK, RIGHT, LEFT = 0, 1, 2, 3, 4, 5

    # Each rotation is defined as:
    # - face_perm: how faces are permuted (new_face[i] = old_face[face_perm[i]])
    # - face_rot: how many 90° rotations to apply to each face's content
    # Format: (face_permutation, face_rotations)

    # Identity
    ROT_IDENTITY = ([0, 1, 2, 3, 4, 5], [0, 0, 0, 0, 0, 0])

    # Rotations around Y-axis (UP-DOWN axis), looking from UP
    # x: 90° CW - FRONT→LEFT, LEFT→BACK, BACK→RIGHT, RIGHT→FRONT
    ROT_Y_90 = ([0, 1, 4, 5, 3, 2], [1, 3, 0, 0, 0, 0])
    ROT_Y_180 = ([0, 1, 3, 2, 5, 4], [2, 2, 0, 0, 0, 0])
    ROT_Y_270 = ([0, 1, 5, 4, 2, 3], [3, 1, 0, 0, 0, 0])

    # Rotations around X-axis (RIGHT-LEFT axis), looking from RIGHT
    # y: 90° CW - UP→FRONT, FRONT→DOWN, DOWN→BACK, BACK→UP
    ROT_X_90 = ([2, 3, 1, 0, 4, 5], [0, 2, 0, 2, 1, 3])
    ROT_X_180 = ([1, 0, 3, 2, 4, 5], [2, 2, 2, 2, 2, 2])
    ROT_X_270 = ([3, 2, 0, 1, 4, 5], [2, 0, 2, 0, 3, 1])

    # Rotations around Z-axis (FRONT-BACK axis), looking from FRONT
    # z: 90° CW - UP→RIGHT, RIGHT→DOWN, DOWN→LEFT, LEFT→UP
    ROT_Z_90 = ([5, 4, 2, 3, 0, 1], [1, 1, 1, 3, 1, 1])
    ROT_Z_180 = ([1, 0, 2, 3, 5, 4], [2, 2, 2, 2, 2, 2])
    ROT_Z_270 = ([4, 5, 2, 3, 1, 0], [3, 3, 3, 1, 3, 3])

    # All 24 rotations (generated by combining basic rotations)
    # We'll compute these programmatically
    _ALL_ROTATIONS: List[Tuple[List[int], List[int]]] = None

    @classmethod
    def _compose_rotations(cls,
                           rot1: Tuple[List[int], List[int]],
                           rot2: Tuple[List[int], List[int]]) -> Tuple[List[int], List[int]]:
        """Compose two rotations: apply rot1 first, then rot2."""
        perm1, rots1 = rot1
        perm2, rots2 = rot2

        # New permutation: new[i] = old[perm1[perm2[i]]]
        new_perm = [perm1[perm2[i]] for i in range(6)]

        # New rotations: combine the rotations
        new_rots = [(rots1[perm2[i]] + rots2[i]) % 4 for i in range(6)]

        return (new_perm, new_rots)

    @classmethod
    def _generate_all_rotations(cls) -> List[Tuple[List[int], List[int]]]:
        """Generate all 24 rotations."""
        if cls._ALL_ROTATIONS is not None:
            return cls._ALL_ROTATIONS

        # Start with identity
        rotations = {tuple(map(tuple, cls.ROT_IDENTITY)): cls.ROT_IDENTITY}

        # Basic generators
        generators = [cls.ROT_Y_90, cls.ROT_X_90, cls.ROT_Z_90]

        # Generate all rotations by repeatedly applying generators
        changed = True
        while changed:
            changed = False
            current_rots = list(rotations.values())
            for rot in current_rots:
                for gen in generators:
                    new_rot = cls._compose_rotations(rot, gen)
                    key = tuple(map(tuple, new_rot))
                    if key not in rotations:
                        rotations[key] = new_rot
                        changed = True

        cls._ALL_ROTATIONS = list(rotations.values())
        return cls._ALL_ROTATIONS

    @classmethod
    def get_all_rotations(cls) -> List[Tuple[List[int], List[int]]]:
        """Get all 24 rotations."""
        return cls._generate_all_rotations()

    @classmethod
    def apply_rotation(cls,
                       state: np.ndarray,
                       rotation: Tuple[List[int], List[int]]) -> np.ndarray:
        """
        Apply a rotation to a cube state.

        Args:
            state: Cube state array of shape (6, 3, 3)
            rotation: Rotation to apply (face_perm, face_rots)

        Returns:
            Rotated state array
        """
        face_perm, face_rots = rotation
        new_state = np.zeros_like(state)

        for new_face in range(6):
            old_face = face_perm[new_face]
            rot_amount = face_rots[new_face]

            # Copy and rotate the face
            new_state[new_face] = np.rot90(state[old_face], k=rot_amount)

        return new_state

    @classmethod
    def apply_rotation_to_flat(cls,
                               flat_state: np.ndarray,
                               rotation_idx: int) -> np.ndarray:
        """
        Apply a rotation to a flattened one-hot state.

        Args:
            flat_state: Flattened one-hot state of shape (324,)
            rotation_idx: Index of rotation to apply (0-23)

        Returns:
            Rotated flattened state
        """
        # Reshape to (6, 3, 3, 6) one-hot format
        one_hot = flat_state.reshape(6, 3, 3, 6)

        # Get rotation
        rotations = cls.get_all_rotations()
        rotation = rotations[rotation_idx % len(rotations)]
        face_perm, face_rots = rotation

        # Apply rotation
        new_one_hot = np.zeros_like(one_hot)
        for new_face in range(6):
            old_face = face_perm[new_face]
            rot_amount = face_rots[new_face]
            new_one_hot[new_face] = np.rot90(one_hot[old_face], k=rot_amount)

        return new_one_hot.reshape(-1)

    @classmethod
    def rotate_action(cls, action: int, rotation_idx: int) -> int:
        """
        Transform an action under a rotation.

        When we rotate the cube, the moves also need to be transformed.
        For example, if we rotate 90° around Y-axis:
        R → F, F → L, L → B, B → R

        Args:
            action: Original action index (0-11)
            rotation_idx: Index of rotation applied to state

        Returns:
            Transformed action index
        """
        rotations = cls.get_all_rotations()
        rotation = rotations[rotation_idx % len(rotations)]
        face_perm, _ = rotation

        # Action to face mapping (assuming actions are ordered R, R', L, L', U, U', D, D', F, F', B, B')
        # Actions 0-1: R (face 4), 2-3: L (face 5), 4-5: U (face 0), 6-7: D (face 1), 8-9: F (face 2), 10-11: B (face 3)
        action_to_face = [4, 4, 5, 5, 0, 0, 1, 1, 2, 2, 3, 3]
        face_to_actions = {4: [0, 1], 5: [2, 3], 0: [4, 5], 1: [6, 7], 2: [8, 9], 3: [10, 11]}

        # Get original face and whether it's prime (counterclockwise)
        orig_face = action_to_face[action]
        is_prime = action % 2 == 1

        # Find where this face goes under the rotation
        # face_perm[new] = old, so we need to find new where face_perm[new] = orig_face
        new_face = None
        for i in range(6):
            if face_perm[i] == orig_face:
                new_face = i
                break

        if new_face is None:
            return action  # Shouldn't happen

        # Get the new action
        new_actions = face_to_actions[new_face]
        return new_actions[1] if is_prime else new_actions[0]


def augment_batch(states: np.ndarray,
                  actions: np.ndarray = None,
                  num_augmentations: int = 1) -> Tuple[np.ndarray, np.ndarray]:
    """
    Augment a batch of states with random rotations.

    Args:
        states: Batch of flattened states, shape (batch_size, 324)
        actions: Optional batch of actions, shape (batch_size,)
        num_augmentations: Number of augmentations per sample

    Returns:
        Tuple of (augmented_states, augmented_actions)
        If actions is None, augmented_actions is None
    """
    batch_size = states.shape[0]
    all_rotations = CubeSymmetry.get_all_rotations()
    num_rotations = len(all_rotations)

    aug_states = []
    aug_actions = [] if actions is not None else None

    for i in range(batch_size):
        for _ in range(num_augmentations):
            # Random rotation
            rot_idx = np.random.randint(0, num_rotations)

            # Apply to state
            aug_state = CubeSymmetry.apply_rotation_to_flat(states[i], rot_idx)
            aug_states.append(aug_state)

            # Apply to action if provided
            if actions is not None:
                aug_action = CubeSymmetry.rotate_action(int(actions[i]), rot_idx)
                aug_actions.append(aug_action)

    aug_states = np.array(aug_states)
    if aug_actions is not None:
        aug_actions = np.array(aug_actions)

    return aug_states, aug_actions
